### Intro: find missing data

In [7]:
import pandas as pd
import numpy as np
import math

In [10]:
# Here's building a function using def: 

def square_root(x): 
    return math.sqrt(x)

In [20]:
# Here's building the same function using lambda
square_root = lambda x : math.sqrt(x)
square_root(169)

13.0

In [1]:
# Use the isnull() method to detect the missing values. The output
# shows True when the value is missing. By adding an index into 
# the dataset, you obtain just the entries that are missing.
# A dataset could represent missing data in several ways. In this 
# example, you see missing data represented as np.NaN (NumPy Not 
# a Number) and the Python None value.

### Intro: fill in missing data

In [2]:
# To fill in missing data use fillna(). For fillna() you need to 
# provide a number. Usually, the mean, median, or mode is used. 
# Let's use the same data set and this time let's fill in missing 
# values with the mean.

In [3]:
# We could also just drop all the NAs, by using dropna()

### Write the equivalent lambda function

In [48]:
# Write the equivalent lambda function for the following def 
# function: 

def f (x): return x**2
print f(8)

64

In [21]:
# equivalent lambda function
l = lambda x: x**2
l(2)

4

### Lab 3.4

In [99]:
# read in the raw data from the github url

data = pd.read_csv("https://raw.githubusercontent.com/suneel0101/lesson-plan/master/crunchbase_monthly_export.csv")

In [100]:
print data.columns.values
data.head()

['permalink' 'name' 'homepage_url' 'category_list' ' market '
 ' funding_total_usd ' 'status' 'country_code' 'state_code' 'region' 'city'
 'funding_rounds' 'founded_at' 'founded_month' 'founded_quarter'
 'founded_year' 'first_funding_at' 'last_funding_at' 'Unnamed: 18']

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,city,funding_rounds,founded_at,founded_month,founded_quarter,founded_year,first_funding_at,last_funding_at,Unnamed: 18
0,/organization/canal-do-credito,Canal do Credito,http://www.canaldocredito.com.br,|Credit|Technology|Services|Finance|,Credit,"750,000",NaN,BRA,NaN,Rio de Janeiro,Belo Horizonte,1,NaN,NaN,NaN,NaN,1/1/10,1/1/10,NaN
1,/organization/waywire,#waywire,http://www.waywire.com,|Entertainment|Politics|Social Media|News|,Entertainment,"1,750,000",acquired,USA,NY,New York City,New York,1,6/1/12,2012-06,2012-Q2,2012.0,6/30/12,6/30/12,NaN
2,/organization/tv-communications,&TV Communications,http://enjoyandtv.com,|Games|,Games,"4,000,000",operating,USA,CA,Los Angeles,Los Angeles,2,NaN,NaN,NaN,NaN,6/4/10,9/23/10,NaN
3,/organization/rock-your-paper,'Rock' Your Paper,http://www.rockyourpaper.org,|Publishing|Education|,Education,"40,000",operating,EST,NaN,Tallinn,Tallinn,1,10/26/12,2012-10,2012-Q4,2012.0,8/9/12,8/9/12,NaN
4,/organization/in-touch-network,(In)Touch Network,http://www.InTouchNetwork.com,|Electronics|Guides|Coffee|Restaurants|Music|i...,Apps,"1,500,000",operating,GBR,NaN,London,London,1,4/1/11,2011-04,2011-Q2,2011.0,4/1/11,4/1/11,NaN

In [101]:
# Renaming column names to remove spaces
data.rename(columns ={" market ":"market"," funding_total_usd ":"funding_total_usd"}, inplace=True)

In [142]:
# find missing values
# replace unwanted characters from funding total USD column
data["funding_total_usd"] = data["funding_total_usd"].replace({',':''}, regex=True)
data["funding_total_usd"] = data["funding_total_usd"].replace({' -   ':'0'}, regex=True)
data["funding_total_usd"] = data["funding_total_usd"].replace({' ':''}, regex=True)

# change data type from string to float
data["funding_total_usd"] = data["funding_total_usd"].astype(float)

# replace 0.0 to nan
data["funding_total_usd"][data["funding_total_usd"] == 0.0] = np.NaN

In [138]:
# fill in missing data with the mean
data["funding_total_usd"] = data["funding_total_usd"].fillna(round(np.mean(data["funding_total_usd"])))

In [145]:
# Zero nan values in funding_total_usd column
print sum(data["funding_total_usd"].isnull())
round(np.mean((data["funding_total_usd"])))

0

18005069.0

In [148]:
# funtion to check number of nan values in the dataframe
def num_missing(x):
    return sum(x.isnull())

data.apply(num_missing, axis=0)

permalink                0
name                     1
homepage_url          3036
category_list         3953
market                3953
funding_total_usd        0
status                2742
country_code          4145
state_code           17177
region                5335
city                  4841
funding_rounds           0
founded_at            9658
founded_month         9724
founded_quarter       9724
founded_year          9724
first_funding_at         0
last_funding_at          0
dtype: int64

In [147]:
# drop last column
data.drop('Unnamed: 18', axis=1, inplace =True)

In [150]:
# check mode of country code column
from scipy.stats import mode
print mode(data['country_code']).mode[0]

# filling nan values in Country code column with Mode value
data['country_code']  = data['country_code'].fillna(mode(data['country_code']).mode[0])

'USA'

In [178]:
# pivot table
pd.pivot_table(data,index=["country_code"],aggfunc=np.sum,values=["funding_total_usd","funding_rounds"])

              funding_rounds  funding_total_usd
country_code
ALB                        1       1.500000e+05
ANT                       13       3.482238e+07
ARE                       59       7.775957e+08
ARG                      213       3.835370e+08
ARM                        4       2.658168e+07
AUS                      430       3.218247e+09
AUT                      164       9.151751e+08
AZE                        4       3.720000e+05
BEL                      223       1.513139e+09
BGD                       11       4.719298e+07
BGR                       93       1.021991e+08
BHR                        4       1.812634e+07
BHS                        3       2.810507e+07
BLR                        3       1.200000e+05
BMU                        6       7.703211e+08
BRA                      377       2.995442e+09
BRB                        1       7.986790e+05
BRN                        1       1.800507e+07
BWA                        1       1.000000e+03
CAN                     1875       1.597638e+10
CHE                      329       3.655425e+09
CHL                      355       1.013553e+08
CHN                     1993       3.538789e+10
CMR                        2       1.195610e+05
COL                       44       2.497900e+08
CRI                        8       1.879907e+07
CSS                        6       5.200030e+06
CYM                       11       1.446781e+08
CYP                       19       6.278664e+07
CZE                       68       5.788137e+08
...                      ...                ...
REU                        2       1.462400e+05
ROM                        2       2.000000e+04
ROU                       52       2.491854e+08
RUS                      537       9.785176e+09
SAU                        6       7.771332e+06
SEN                        1       1.500000e+05
SGP                      392       2.250344e+09
SLV                        4       4.400000e+05
SOM                        1       2.000000e+06
SRB                        2       1.802432e+07
SVK                       14       1.041798e+07
SVN                       11       3.601888e+06
SWE                      438       2.951124e+09
SWZ                        1       1.000000e+07
SYC                        1       3.500000e+04
THA                       44       2.274423e+08
TUN                        4       2.197507e+07
TUR                      147       1.053531e+09
TWN                       55       9.453966e+08
TZA                        2       7.180000e+06
UGA                       10       5.543921e+07
UKR                       47       1.651756e+08
URY                       13       3.815014e+07
USA                    54586       6.217333e+11
UZB                        1       9.000000e+04
VEN                        2       9.007700e+04
VNM                       21       3.074763e+08
ZAF                       62       5.057250e+08
ZMB                        1       4.000000e+06
ZWE                        1       1.000000e+07

[127 rows x 2 columns]

In [176]:
# pd.pivot_table(data,index=["country_code","market"])

pd.pivot_table(data,index=["country_code"],columns=["status"],values=["funding_total_usd","funding_rounds","founded_year"],
               aggfunc=[np.mean])

                          mean                                             \
             funding_total_usd                             funding_rounds
status                acquired        closed     operating       acquired
country_code
ALB                        NaN           NaN  1.500000e+05            NaN
ANT                        NaN           NaN  3.869154e+06            NaN
ARE               1.481630e+07  1.200505e+07  1.373276e+07       1.000000
ARG               6.566250e+06  4.721948e+06  2.513428e+06       2.250000
ARM                        NaN           NaN  1.329084e+07            NaN
AUS               8.396521e+06  7.217669e+06  1.030488e+07       1.400000
AUT               1.493914e+07  6.165912e+06  8.956964e+06       1.750000
AZE                        NaN           NaN  1.240000e+05            NaN
BEL               3.259691e+07  4.344596e+06  8.609524e+06       1.750000
BGD                        NaN           NaN  9.438595e+06            NaN
BGR               1.076910e+05           NaN  1.182992e+06       1.500000
BHR                        NaN  1.800507e+07  6.063450e+04            NaN
BHS                        NaN           NaN  9.368356e+06            NaN
BLR                        NaN           NaN  1.500000e+04            NaN
BMU               1.800507e+07           NaN  7.521667e+07       1.000000
BRA               6.840203e+07  7.696597e+06  1.193973e+07       1.200000
BRB                        NaN           NaN  7.986790e+05            NaN
BRN                        NaN           NaN  1.800507e+07            NaN
BWA                        NaN           NaN  1.000000e+03            NaN
CAN               1.590886e+07  8.622345e+06  1.149542e+07       1.806818
CHE               6.950400e+07  8.405279e+06  1.510041e+07       1.800000
CHL               1.201171e+07  1.466500e+06  2.008858e+05       1.000000
CHN               6.034151e+07  8.096702e+06  2.976384e+07       2.173913
CMR                        NaN           NaN  5.978050e+04            NaN
COL                        NaN           NaN  9.531827e+06            NaN
CRI                        NaN  3.500000e+05  4.612267e+06            NaN
CSS                        NaN           NaN  8.666717e+05            NaN
CYM                        NaN           NaN  9.959762e+06            NaN
CYP                        NaN           NaN  6.278664e+06            NaN
CZE               2.527769e+07  2.583333e+04  1.045569e+07       1.333333
...                        ...           ...           ...            ...
REU                        NaN           NaN  1.462400e+05            NaN
ROM                        NaN           NaN  2.000000e+04            NaN
ROU                        NaN  2.331000e+05  8.914952e+06            NaN
RUS               1.525253e+07  5.858591e+06  5.199387e+07       1.750000
SAU                        NaN  6.000000e+06  1.928330e+05            NaN
SEN                        NaN           NaN  1.500000e+05            NaN
SGP               1.039887e+07  1.193659e+07  8.006478e+06       2.400000
SLV                        NaN           NaN  1.466667e+05            NaN
SOM                        NaN  2.000000e+06           NaN            NaN
SRB                        NaN           NaN  1.925200e+04            NaN
SVK                        NaN           NaN  9.470891e+05            NaN
SVN                        NaN  2.520400e+05  3.722053e+05            NaN
SWE               7.740741e+06  8.242548e+06  1.007221e+07       1.250000
SWZ                        NaN           NaN  1.000000e+07            NaN
SYC                        NaN  3.500000e+04           NaN            NaN
THA               2.000000e+06  4.510000e+06  6.498008e+06       1.000000
TUN                        NaN           NaN  7.325023e+06            NaN
TUR               3.110000e+07  9.052534e+06  9.928634e+06       2.000000
TWN                        NaN  1.558500e+05  2.147272e+07            NaN
TZA                        NaN           NaN  3.590000e+06            NaN
UGA                        NaN  1.000000e+05  6.148801e+06            NaN
UKR                        NaN           NaN  3.491012e+06            NaN
URY               1.000000e+06           NaN  4.560642e+06       1.000000
USA               2.372194e+07  1.190343e+07  1.662484e+07       2.042603
UZB                        NaN           NaN  9.000000e+04            NaN
VEN                        NaN           NaN  9.007700e+04            NaN
VNM                        NaN  3.500000e+06  1.899852e+07            NaN
ZAF               1.157753e+07  1.480000e+05  1.120535e+07       1.000000
ZMB                        NaN           NaN  4.000000e+06            NaN
ZWE                        NaN           NaN  1.000000e+07            NaN


                                 founded_year
status          closed operating     acquired       closed    operating
country_code
ALB                NaN  1.000000          NaN          NaN  2012.000000
ANT                NaN  1.444444          NaN          NaN  2010.714286
ARE           1.000000  1.225000  2005.000000  2010.000000  2009.815789
ARG           1.000000  1.549550  2007.666667  2009.625000  2009.816327
ARM                NaN  2.000000          NaN          NaN  2008.500000
AUS           1.437500  1.429688  2004.625000  2009.333333  2008.304762
AUT           1.333333  1.647059  2005.250000  2008.428571  2008.573529
AZE                NaN  1.333333          NaN          NaN  2012.000000
BEL           1.285714  1.507812  2003.833333  2005.000000  2007.880435
BGD                NaN  2.200000          NaN          NaN  2009.600000
BGR                NaN  1.574074  2010.500000          NaN  2011.311111
BHR           1.000000  1.500000          NaN  2011.000000  2012.500000
BHS                NaN  1.000000          NaN          NaN  2010.000000
BLR                NaN  1.000000          NaN          NaN  2010.000000
BMU                NaN  1.333333  2001.000000          NaN  2000.000000
BRA           1.105263  1.510309  2000.800000  2007.666667  2010.055215
BRB                NaN  1.000000          NaN          NaN  2007.000000
BRN                NaN  1.000000          NaN          NaN  2013.000000
BWA                NaN  1.000000          NaN          NaN  2013.000000
CAN           1.453333  1.559662  2004.116883  2004.596491  2007.184106
CHE           1.000000  1.572222  2002.285714  2007.750000  2007.126667
CHL           1.750000  1.134483  2010.500000  2009.750000  2011.807910
CHN           1.187500  1.690712  2003.000000  2007.882353  2005.344710
CMR                NaN  1.000000          NaN          NaN  2011.500000
COL                NaN  1.458333          NaN          NaN  2009.100000
CRI           1.000000  1.750000          NaN  2009.000000  2009.333333
CSS                NaN  1.000000          NaN          NaN  2010.000000
CYM                NaN  1.250000          NaN          NaN  2007.600000
CYP                NaN  1.900000          NaN          NaN  2007.625000
CZE           1.000000  1.238095  2006.000000  2011.666667  2009.085714
...                ...       ...          ...          ...          ...
REU                NaN  2.000000          NaN          NaN  2008.000000
ROM                NaN  2.000000          NaN          NaN  2013.000000
ROU           1.000000  1.333333          NaN  2009.000000  2010.120000
RUS           1.888889  1.544872  2004.750000  2009.000000  2009.855072
SAU           1.000000  1.000000          NaN  2005.000000  2012.500000
SEN                NaN  1.000000          NaN          NaN  2011.000000
SGP           1.333333  1.438819  2007.600000  2007.571429  2009.870647
SLV                NaN  1.333333          NaN          NaN  2009.666667
SOM           1.000000       NaN          NaN  2010.000000          NaN
SRB                NaN  1.000000          NaN          NaN  2014.000000
SVK                NaN  1.272727          NaN          NaN  2008.666667
SVN           1.000000  1.111111          NaN  2008.000000  2011.666667
SWE           1.285714  1.455939  2001.600000  2003.818182  2006.752632
SWZ                NaN  1.000000          NaN          NaN          NaN
SYC           1.000000       NaN          NaN  2011.000000          NaN
THA           1.000000  1.235294  2009.000000  1999.000000  2008.500000
TUN                NaN  1.333333          NaN          NaN  2008.000000
TUR           1.000000  1.432099  2011.000000  2008.000000  2009.075758
TWN           1.000000  1.405405          NaN  2011.000000  2006.555556
TZA                NaN  1.000000          NaN          NaN          NaN
UGA           1.000000  1.000000          NaN  2009.000000  2011.500000
UKR                NaN  1.142857          NaN          NaN  2011.281250
URY                NaN  1.125000  1986.000000          NaN  2011.166667
USA           1.536239  1.749155  2003.620106  2007.342325  2007.279135
UZB                NaN  1.000000          NaN          NaN  2006.000000
VEN                NaN  2.000000          NaN          NaN          NaN
VNM           1.000000  1.250000          NaN  2007.000000  2009.636364
ZAF           1.400000  1.232558  2005.000000  2010.500000  2006.722222
ZMB                NaN  1.000000          NaN          NaN          NaN
ZWE                NaN  1.000000          NaN          NaN          NaN

[127 rows x 9 columns]

In [180]:
pd.pivot_table(data,index=["market"],columns=["status"],values=["funding_total_usd","funding_rounds","founded_year"],
               aggfunc=[np.mean])

                                                  mean                \
                                     funding_total_usd
status                                        acquired        closed
market
 3D                                       1.112592e+07  4.234178e+06
 3D Printing                                       NaN           NaN
 3D Technology                                     NaN           NaN
 Accounting                               3.672500e+06  1.800507e+07
 Active Lifestyle                                  NaN           NaN
 Ad Targeting                             2.285623e+07  5.875000e+05
 Advanced Materials                                NaN           NaN
 Adventure Travel                                  NaN  1.800507e+07
 Advertising                              1.799518e+07  6.037773e+06
 Advertising Exchanges                             NaN           NaN
 Advertising Networks                     1.300000e+06  5.000000e+06
 Advertising Platforms                             NaN           NaN
 Advice                                   1.430000e+07  9.069700e+06
 Aerospace                                9.100000e+07           NaN
 Agriculture                              6.035000e+07           NaN
 Algorithms                                        NaN           NaN
 All Markets                              1.800507e+07  3.750000e+06
 All Students                             7.160023e+06  6.797780e+06
 Alternative Medicine                              NaN           NaN
 Alumni                                            NaN  2.000000e+04
 Analytics                                1.331625e+07  1.027054e+07
 Android                                  9.864486e+06  7.519576e+06
 Angels                                            NaN           NaN
 Animal Feed                                       NaN           NaN
 App Marketing                            5.708902e+06  2.810000e+06
 App Stores                               1.647002e+07  1.580203e+07
 Application Performance Monitoring                NaN           NaN
 Application Platforms                             NaN           NaN
 Apps                                     1.403997e+07  5.373861e+06
 Aquaculture                                       NaN           NaN
...                                                ...           ...
 Therapeutics                                      NaN           NaN
 Ticketing                                         NaN           NaN
 Tourism                                           NaN           NaN
 Toys                                              NaN           NaN
 Tracking                                 6.500000e+06           NaN
 Trading                                           NaN           NaN
 Transportation                                    NaN  1.000000e+04
 Travel                                   2.258002e+07  6.728523e+06
 Travel & Tourism                         1.400000e+07           NaN
 User Experience Design                            NaN           NaN
 Utilities                                         NaN           NaN
 Venture Capital                                   NaN           NaN
 Veterinary                                        NaN           NaN
 Video                                             NaN           NaN
 Video Games                                       NaN           NaN
 Video Streaming                                   NaN           NaN
 Video on Demand                                   NaN           NaN
 VoIP                                              NaN           NaN
 Web Design                                        NaN           NaN
 Web Development                                   NaN           NaN
 Web Hosting                              3.084632e+07  1.443577e+07
 Web Tools                                4.000000e+06           NaN
 Weddings                                          NaN           NaN
 Wholesale                                         NaN           NaN
 Wine And Spirits                                  NaN           NaN
 Wireless                                          NaN           NaN
 iOS                                               NaN           NaN
 iPad                                     1.267632e+06  4.765000e+06
 iPhone                                   9.800000e+06  6.693356e+06
 mHealth                                           NaN           NaN

                                                                             \
                                                   funding_rounds
status                                   operating       acquired    closed
market
 3D                                   1.079758e+07       1.800000  1.333333
 3D Printing                          4.640012e+06            NaN       NaN
 3D Technology                        1.800507e+07            NaN       NaN
 Accounting                           2.289110e+07       2.333333  1.000000
 Active Lifestyle                     4.100833e+06            NaN       NaN
 Ad Targeting                         2.882661e+07       2.125000  1.000000
 Advanced Materials                   3.675253e+07            NaN       NaN
 Adventure Travel                     3.992274e+06            NaN  1.000000
 Advertising                          1.230512e+07       2.383420  1.421384
 Advertising Exchanges                2.648729e+07            NaN       NaN
 Advertising Networks                 2.275441e+06       1.000000  1.000000
 Advertising Platforms                1.067538e+08            NaN       NaN
 Advice                               6.331692e+06       2.000000  1.250000
 Aerospace                            9.766192e+06       3.000000       NaN
 Agriculture                          7.846740e+06       2.500000       NaN
 Algorithms                           6.188723e+06            NaN       NaN
 All Markets                          6.883501e+06       1.000000  2.000000
 All Students                         6.379049e+07       1.666667  1.250000
 Alternative Medicine                 6.200000e+06            NaN       NaN
 Alumni                               2.584202e+06            NaN  1.000000
 Analytics                            1.273450e+07       2.318182  1.676471
 Android                              8.492569e+06       2.225806  1.250000
 Angels                               2.019424e+06            NaN       NaN
 Animal Feed                          8.556690e+06            NaN       NaN
 App Marketing                        8.219545e+06       1.000000  2.000000
 App Stores                           5.680472e+06       2.666667  1.200000
 Application Performance Monitoring   2.009890e+07            NaN       NaN
 Application Platforms                3.420670e+07            NaN       NaN
 Apps                                 7.359354e+06       2.625000  1.451613
 Aquaculture                          7.500000e+05            NaN       NaN
...                                            ...            ...       ...
 Therapeutics                         6.300000e+06            NaN       NaN
 Ticketing                            5.098787e+06            NaN       NaN
 Tourism                              9.143131e+06            NaN       NaN
 Toys                                 3.600000e+05            NaN       NaN
 Tracking                             8.106667e+06       2.000000       NaN
 Trading                              4.000000e+04            NaN       NaN
 Transportation                       1.607140e+07            NaN  1.000000
 Travel                               1.629758e+07       2.000000  1.117647
 Travel & Tourism                     1.216578e+07       4.000000       NaN
 User Experience Design               2.500000e+04            NaN       NaN
 Utilities                            3.460417e+07            NaN       NaN
 Venture Capital                      1.800000e+07            NaN       NaN
 Veterinary                           1.800507e+07            NaN       NaN
 Video                                1.367255e+07            NaN       NaN
 Video Games                          6.138376e+06            NaN       NaN
 Video Streaming                      9.627534e+06            NaN       NaN
 Video on Demand                      6.389987e+06            NaN       NaN
 VoIP                                 1.925253e+07            NaN       NaN
 Web Design                           1.380338e+07            NaN       NaN
 Web Development                      9.167600e+06            NaN       NaN
 Web Hosting                          2.279869e+07       2.184211  1.576923
 Web Tools                                     NaN       4.000000       NaN
 Weddings                             8.510023e+06            NaN       NaN
 Wholesale                            1.260228e+06            NaN       NaN
 Wine And Spirits                     1.110718e+07            NaN       NaN
 Wireless                             1.961250e+07            NaN       NaN
 iOS                                  2.355119e+06            NaN       NaN
 iPad                                 6.176362e+06       1.000000  1.500000
 iPhone                               5.779227e+06       2.000000  1.222222
 mHealth                              1.219390e+05            NaN       NaN

                                                                          \
                                               founded_year
status                               operating     acquired       closed
market
 3D                                   1.574074  2001.750000  2009.800000
 3D Printing                          1.833333          NaN          NaN
 3D Technology                        1.000000          NaN          NaN
 Accounting                           2.283019  2007.833333  2009.000000
 Active Lifestyle                     1.666667          NaN          NaN
 Ad Targeting                         2.657143  2007.250000  2008.500000
 Advanced Materials                   2.000000          NaN          NaN
 Adventure Travel                     1.642857          NaN  2011.000000
 Advertising                          1.902303  2006.011429  2008.374046
 Advertising Exchanges                2.666667          NaN          NaN
 Advertising Networks                 1.000000  2008.000000  2008.000000
 Advertising Platforms                2.100000          NaN          NaN
 Advice                               1.466667  2005.000000  2010.000000
 Aerospace                            1.894737  2009.000000          NaN
 Agriculture                          2.500000  2002.500000          NaN
 Algorithms                           1.692308          NaN          NaN
 All Markets                          1.875000  2005.000000  2007.000000
 All Students                         1.884615  2008.333333  2009.000000
 Alternative Medicine                 1.000000          NaN          NaN
 Alumni                               1.800000          NaN          NaN
 Analytics                            2.013670  2006.926829  2007.846154
 Android                              1.854785  2008.466667  2009.740741
 Angels                               1.142857          NaN          NaN
 Animal Feed                          1.333333          NaN          NaN
 App Marketing                        1.437500  2004.500000  2011.000000
 App Stores                           1.812500  1999.666667  2007.800000
 Application Performance Monitoring   3.333333          NaN          NaN
 Application Platforms                2.000000          NaN          NaN
 Apps                                 1.706704  2008.090909  2008.566667
 Aquaculture                          1.000000          NaN          NaN
...                                        ...          ...          ...
 Therapeutics                         2.000000          NaN          NaN
 Ticketing                            1.333333          NaN          NaN
 Tourism                              1.333333          NaN          NaN
 Toys                                 4.000000          NaN          NaN
 Tracking                             4.000000          NaN          NaN
 Trading                              1.000000          NaN          NaN
 Transportation                       1.074627          NaN  2012.000000
 Travel                               1.467033  2006.111111  2009.500000
 Travel & Tourism                     1.166667  1999.000000          NaN
 User Experience Design               1.000000          NaN          NaN
 Utilities                            1.200000          NaN          NaN
 Venture Capital                      2.000000          NaN          NaN
 Veterinary                           1.000000          NaN          NaN
 Video                                1.000000          NaN          NaN
 Video Games                          1.375000          NaN          NaN
 Video Streaming                      1.000000          NaN          NaN
 Video on Demand                      4.000000          NaN          NaN
 VoIP                                 1.000000          NaN          NaN
 Web Design                           1.000000          NaN          NaN
 Web Development                      1.500000          NaN          NaN
 Web Hosting                          1.643939  2000.915254  2001.200000
 Web Tools                                 NaN  1998.000000          NaN
 Weddings                             1.333333          NaN          NaN
 Wholesale                            1.000000          NaN          NaN
 Wine And Spirits                     1.142857          NaN          NaN
 Wireless                             1.000000          NaN          NaN
 iOS                                  1.636364          NaN          NaN
 iPad                                 1.642857  2010.000000  2009.000000
 iPhone                               1.241379  2010.000000  2008.000000
 mHealth                              1.500000          NaN          NaN



status                                  operating
market
 3D                                   2008.886792
 3D Printing                          2012.166667
 3D Technology                        2013.000000
 Accounting                           2008.100000
 Active Lifestyle                     2011.600000
 Ad Targeting                         2008.794118
 Advanced Materials                   2007.500000
 Adventure Travel                     2010.571429
 Advertising                          2008.636434
 Advertising Exchanges                2011.000000
 Advertising Networks                 2011.625000
 Advertising Platforms                2007.300000
 Advice                               2008.571429
 Aerospace                            2010.357143
 Agriculture                          2009.142857
 Algorithms                           2010.000000
 All Markets                          2005.333333
 All Students                         2009.836735
 Alternative Medicine                 2013.000000
 Alumni                               2008.200000
 Analytics                            2009.030516
 Android                              2010.065744
 Angels                               2007.857143
 Animal Feed                          2011.666667
 App Marketing                        2007.031250
 App Stores                           2009.750000
 Application Performance Monitoring   2008.333333
 Application Platforms                2007.000000
 Apps                                 2010.584570
 Aquaculture                          2013.000000
...                                           ...
 Therapeutics                         2013.000000
 Ticketing                            2008.333333
 Tourism                              2012.500000
 Toys                                 2009.000000
 Tracking                             2010.666667
 Trading                              2013.000000
 Transportation                       2009.354839
 Travel                               2008.303448
 Travel & Tourism                     2011.400000
 User Experience Design               2014.000000
 Utilities                            2007.250000
 Venture Capital                      2011.000000
 Veterinary                                   NaN
 Video                                2009.875000
 Video Games                          2005.000000
 Video Streaming                      2009.333333
 Video on Demand                      2007.000000
 VoIP                                 1999.000000
 Web Design                           2005.000000
 Web Development                      2010.333333
 Web Hosting                          2002.664865
 Web Tools                                    NaN
 Weddings                             2013.000000
 Wholesale                            2010.000000
 Wine And Spirits                     2011.285714
 Wireless                             2012.000000
 iOS                                  2010.700000
 iPad                                 2010.538462
 iPhone                               2010.148148
 mHealth                              2012.000000

[538 rows x 9 columns]